### ISSUE TITLE
Issues installing guillotine-solver package

### ISSUE THREAD

**Issue by ruswerner** [sbnedkov/cutlist#1]
I am trying to get this app running locally and can't access this package dependency on bitbucket.

    "guillotine-solver": "bitbucket:/%2Fsnedkov%2Fguillotine-solver"

Would you be able to open access to this or put it on github? Cheers!

**Comment by sbnedkov** [comment]
Hi @ruswerner , I'm a bit embarassed because this is a product we are developing and the front end should probably be private too. That said - if you are interested in seeing the front end in action I can try to open source one of the first versions of the guillotine solver. Have in mind that we didn't solve the guillotine cut, we are still working on it so even latest module is not production ready. :)

**Comment by ruswerner** [comment]
Hi @sbnedkov. No worries. In the meantime I found a great python lib called `rectpack` and have been using that via nodejs to do bin packing. Thanks anyway and best of luck with your product!

**Comment by nischayn22** [comment]
Is this library public yet?

**Comment by sbnedkov** [comment]
No, @nischayn22 , but if you are interested I can open source a version from before a couple of years to give you a feel of how the application looks like in action. Are you interested in the application or the algorithm itself?

**Comment by nischayn22** [comment]
I am interested in both but would like to see it in action first. Would be
great if you can make it open source.

**Comment by sbnedkov** [comment]
Ok, I’ll try to organize something next week. Can you please open a new issue to track that?

**Comment by matak** [comment]
it seems that new issue was not opened yet? :) still alive this project? any youtube video for example form how it work?

**Comment by sbnedkov** [comment]
Hey @matak , I'm sorry, I'm really busy these days, but the direction would be that I will remove this project from Github. Anyway, this is just the frontend. If you can let me know what you are interested in I might be able to give you more information.

**Comment by sbnedkov** [comment]
Hey, sorry for the delay, but a basic version of the guillotine solver is opened now on [Guillotine solver](https://github.com/sbnedkov/guillotine-solver). End to end application can be ran from `gpl2` branch of this project, you'll need a running MongoDB database. Cheers!
